import {
  DashboardOutlined,
  QuestionCircleOutlined,
  TrophyOutlined,
  TeamOutlined,
  TagOutlined,
  FolderOutlined,
  SolutionOutlined,
  PieChartOutlined,
  AppstoreOutlined,
  BookOutlined,
  CalendarOutlined,
  NotificationOutlined,
  TableOutlined,
  FileTextOutlined,
  AuditOutlined,
  UserOutlined,
  ApartmentOutlined,
  SettingOutlined,
} from "@ant-design/icons";
import { APP_PREFIX_PATH } from "configs/AppConfig";

const dashBoardNavTree = [
  {
    key: "home",
    path: `${APP_PREFIX_PATH}/modules/home`,
    title: "sidenav.apps.dashboard",
    icon: DashboardOutlined,
    breadcrumb: false,
    submenu: [],
    module: "modules/home",
  },
  {
    key: "system.organizations",
    path: `${APP_PREFIX_PATH}/modules/system/organizations`,
    title: "sidenav.apps.system.organization",
    icon: ApartmentOutlined,
    breadcrumb: false,
    submenu: [],
    module: "modules/system",
  },
  {
    key: "class",
    path: `${APP_PREFIX_PATH}/modules/system/classes`,
    title: "sidenav.apps.classes",
    icon: TeamOutlined,
    breadcrumb: false,
    submenu: [],
    module: "modules/system",
  },
  {
    key: "system.users",
    path: `${APP_PREFIX_PATH}/modules/system/users`,
    title: "sidenav.apps.system.user",
    icon: UserOutlined,
    breadcrumb: false,
    submenu: [],
    module: "modules/system",
  },
  {
    key: "system.catalogs",
    path: `${APP_PREFIX_PATH}/modules/system/catalogs`,
    title: "sidenav.apps.system.catalog",
    icon: FolderOutlined,
    breadcrumb: false,
    submenu: [],
    module: "modules/system",
  },
  {
    key: "system.setting",
    path: `${APP_PREFIX_PATH}/modules/system/setting`,
    title: "sidenav.apps.system.setting",
    icon: SettingOutlined,
    breadcrumb: false,
    submenu: [],
    module: "modules/system",
  },
];

const lessonPlanNav = [
  {
    key: "lessonplan",
    title: "sidenav.apps.modules.lessonplan",
    icon: BookOutlined,
    breadcrumb: false,
    module: "mylesson",
    submenu: [
      {
        key: "lessonplans.myplans",
        path: `${APP_PREFIX_PATH}/modules/mylesson/lessonplans/myplans`,
        title: "sidenav.apps.modules.lessonplan.myplan",
        icon: BookOutlined,
        breadcrumb: false,
        submenu: [],
        module: "mylesson",
      },
      {
        key: "lessonplans.assignedplans",
        path: `${APP_PREFIX_PATH}/modules/mylesson/lessonplans/assignedplans`,
        title: "sidenav.apps.modules.lessonplan.assignedplan",
        icon: AuditOutlined,
        breadcrumb: false,
        submenu: [],
        module: "mylesson",
      },
    ],
  },
  {
    key: "lib",
    title: "sidenav.apps.modules.lib",
    icon: BookOutlined,
    breadcrumb: false,
    module: "mylesson",
    submenu: [
      {
        key: "lib_material.lib",
        path: `${APP_PREFIX_PATH}/modules/mylesson/library`,
        title: "sidenav.apps.modules.mylesson.library",
        icon: BookOutlined,
        breadcrumb: false,
        submenu: [],
        module: "mylesson",
      },
      {
        key: "lib_material.libCategory",
        path: `${APP_PREFIX_PATH}/modules/mylesson/librarycategory`,
        title: "sidenav.apps.modules.mylesson.libraryCategory",
        icon: FolderOutlined,
        breadcrumb: false,
        submenu: [],
        module: "mylesson",
      },
    ],
  },
  {
    key: "material",
    title: "sidenav.apps.modules.material",
    icon: BookOutlined,
    breadcrumb: false,
    module: "mylesson",
    submenu: [
      {
        key: "lib_material.material",
        path: `${APP_PREFIX_PATH}/modules/mylesson/material`,
        title: "sidenav.apps.modules.mylesson.material",
        icon: AuditOutlined,
        breadcrumb: false,
        submenu: [],
        module: "mylesson",
      },
      {
        key: "lib_material.materialCategory",
        path: `${APP_PREFIX_PATH}/modules/mylesson/materialcategory`,
        title: "sidenav.apps.modules.mylesson.materialCategory",
        icon: FolderOutlined,
        breadcrumb: false,
        submenu: [],
        module: "mylesson",
      },
    ],
  },
];

const managementNav = [
  {
    key: "myoffice",
    title: "sidenav.apps.modules.myOffice.management",
    icon: BookOutlined,
    breadcrumb: false,
    module: "myoffice",
    submenu: [
      {
        key: "attendance.dashboard",
        path: `${APP_PREFIX_PATH}/modules/myoffice/attendances/dashboard`,
        title: "sidenav.apps.modules.attendance",
        icon: DashboardOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
      {
        key: "timetable",
        path: `${APP_PREFIX_PATH}/modules/myoffice/timetable`,
        title: "sidenav.apps.modules.timetable",
        icon: TableOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
      {
        key: "announcement",
        path: `${APP_PREFIX_PATH}/modules/myoffice/announcement`,
        title: "sidenav.apps.modules.announcement",
        icon: NotificationOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
      {
        key: "document",
        path: `${APP_PREFIX_PATH}/modules/myoffice/document`,
        title: "sidenav.apps.modules.document",
        icon: FileTextOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
    ],
  },
];

const tasksNav = [
  {
    key: "modules.task",
    title: "sidenav.apps.modules.task",
    icon: BookOutlined,
    breadcrumb: false,
    module: "myoffice",
    submenu: [
      {
        key: "task/dashboard",
        path: `${APP_PREFIX_PATH}/modules/myoffice/task/dashboard`,
        title: "sidenav.apps.modules.tasks.dashboard",
        icon: DashboardOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
      {
        key: "task/project",
        path: `${APP_PREFIX_PATH}/modules/myoffice/task/project`,
        title: "sidenav.apps.modules.tasks.project",
        icon: AppstoreOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
      {
        key: "task/list",
        path: `${APP_PREFIX_PATH}/modules/myoffice/task/list`,
        title: "sidenav.apps.modules.tasks.list",
        icon: CalendarOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
      {
        key: "task/report",
        path: `${APP_PREFIX_PATH}/modules/myoffice/task/report`,
        title: "sidenav.apps.modules.tasks.report",
        icon: PieChartOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
    ],
  },
];

const postNav = [
  {
    key: "mypostoffice",
    title: "sidenav.modules.posts",
    icon: BookOutlined,
    breadcrumb: false,
    module: "myoffice",
    submenu: [
      {
        key: "post",
        path: `${APP_PREFIX_PATH}/modules/myoffice/news/posts`,
        title: "sidenav.apps.post",
        icon: TagOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
      {
        key: "postCategories",
        path: `${APP_PREFIX_PATH}/modules/myoffice/news/postcategories`,
        title: "sidenav.apps.postCategory",
        icon: FolderOutlined,
        breadcrumb: false,
        submenu: [],
        module: "myoffice",
      },
    ],
  },
];

const examNav = [
  {
    key: "mystudies",
    title: "sidenav.modules.assignments",
    icon: BookOutlined,
    breadcrumb: false,
    module: "mystudies",
    submenu: [
      {
        key: "exam",
        path: `${APP_PREFIX_PATH}/modules/mystudies/exams`,
        title: "sidenav.apps.exam",
        icon: TrophyOutlined,
        breadcrumb: false,
        submenu: [],
        module: "mystudies",
      },
      {
        key: "questionCatalog",
        title: "sidenav.apps.questionCatalog",
        breadcrumb: true,
        path: `${APP_PREFIX_PATH}/modules/mystudies/exams/questioncatalogs`,
        icon: QuestionCircleOutlined,
        submenu: [],
        module: "mystudies",
      },
      {
        key: "examCategories",
        title: "sidenav.apps.examCategories",
        breadcrumb: true,
        path: `${APP_PREFIX_PATH}/modules/mystudies/exams/examcategories`,
        icon: FolderOutlined,
        submenu: [],
        module: "mystudies",
      },
    ],
  },
];

const courseNav = [
  {
    key: "courses",
    title: "sidenav.modules.courses",
    icon: BookOutlined,
    breadcrumb: false,
    module: "mystudies",
    submenu: [
      {
        key: "courses",
        title: "sidenav.apps.courses",
        breadcrumb: true,
        path: `${APP_PREFIX_PATH}/modules/mystudies/courses`,
        icon: BookOutlined,
        submenu: [],
        module: "mystudies",
      },
      {
        key: "courseCategories",
        title: "sidenav.apps.courseCategories",
        breadcrumb: true,
        path: `${APP_PREFIX_PATH}/modules/mystudies/courses/coursecategories`,
        icon: FolderOutlined,
        submenu: [],
        module: "mystudies",
      },
    ],
  },
];

const navigationConfig = [
  ...dashBoardNavTree,
  ...lessonPlanNav,
  ...managementNav,
  ...tasksNav,
  ...postNav,
  ...examNav,
  ...courseNav,
];

export default navigationConfig;
